pull_request_rules:
  - name: Automatic merge when the pull request has been approved (Master Branch).
    conditions:
      - base=master
      - "#approved-reviews-by>=2"
    actions:
      merge:
        method: squash
  - name: Automatic merge when the pull request has been approved (Documentation Branch).
    conditions:
      - base=documentation
      - "#approved-reviews-by>=2"
    actions:
      merge:
        method: squash
  - name: Automatic merge when the pull request is made by SeMiD (Master Branch).
    conditions:
      - base=master
      - author=SeMiD
    actions:
      merge:
        method: squash
  - name: Automatic merge when the pull request is made by SeMiD (Documentation Branch).
    conditions:
      - base=documentation
      - author=SeMiD
    actions:
      merge:
        method: squash
