files:
  - source: /*.md
    translation: /%two_letters_code%/**/%original_file_name%
  - source: /dev/**/*.md
    translation: /%two_letters_code%/dev/**/%original_file_name%
  - source: /install/**/*.md
    translation: /%two_letters_code%/install/**/%original_file_name%
