files:
  - source: /src/Extension/*.json
    translation: /%locale_with_underscore%/Extension/%original_file_name%
  - source: /src/Website/*.json
    translation: /%locale_with_underscore%/Website/%original_file_name%
  - source: /src/Presence/*.json
    translation: /%locale_with_underscore%/Presence/%original_file_name%
    - source: /src/Website/MerchStore/*.json
    translation: /%locale_with_underscore%/Website/MerchStore/%original_file_name%
