files:
  - source: /src/Extension/*.json
    translation: /%locale%/Extension/%original_file_name%
    update_option: update_as_unapproved
  - source: /src/Website/*.json
    translation: /%locale%/Website/%original_file_name%
    update_option: update_as_unapproved
  - source: /src/Presence/*.json
    translation: /%locale%/Presence/%original_file_name%
    update_option: update_as_unapproved
